### ISSUE TITLE
FloatingTabSwitch usuwa ContentScale w Image

### ISSUE THREAD

**Issue by skrapi2011** [Reservant-inc/reservant-mobile#106]
W zakładce RestaurantDetailActivity gdy przełączymy się na wydarzenia, następnie gdy wrócimy do Menu, to wszystkie zdjęcia z MenuItemCard stracą formatowanie.
+ Prawdopodobnie FloatingTabSwitch nadpisuje formatowanie
+ Błąd dotyczy PR #103 
jak i opartego na nim #105

**Comment by Bambi54** [comment]
jeszcze można spróbować https://github.com/coil-kt/coil/issues/909, chociaż nie wiem gdzie ten scale(Scale.FILL) miałby wejść

**Comment by Mroxny** [comment]
Postaram się tym zająć jak znajdę troche czasu
