### ISSUE TITLE
[BUG]RegisterVM ignoruje niepasujące hasła

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-mobile#12]
Funcja `validateForm()` w RegisterViewModel ignoruje niepasujące powtórzenie hasła

**Comment by Bambi54** [comment]
chodzi o to ze validate nie sprawdza czy password i confirmPassword sa takie same? można dodać ale nie jest to jakieś kluczowe na dziś, i tak większość walidacji będzie poprawiana
