### ISSUE TITLE
[BUG]: Nie działa rejestracja użytkownika

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-mobile#181]
- [X] **__Sprawdziłem i nikt nie zgłosił jeszcze takiego błędu na issues__**

## Opisz błąd
Formularz utworzenia konta nie przepuszcza dalej z powodu złego numeru tel mimo że jest wpisany poprawny.
Odpowiedź od backendu:
*The phone number must start with '+' followed by digits.*

**Comment by Bambi54** [comment]
odpowiedź dostajemy od backendu czy to na mobilce zwracamy? jeśli od backu to raczej w innym repo to issue

**Comment by Mroxny** [comment]
To jest odpowiedź od backendu ale słuszna. W mobilce źle wysyłamy dane:
`"phoneNumber":"500100100"`
