### ISSUE TITLE
[BUG]: Edit employee nie zapisuje zmian

### ISSUE THREAD

**Issue by s24937** [Reservant-inc/reservant-mobile#197]
## Opisz błąd
Dla właściciela restauracji JD, dla wybranej restauracji, Edit employee w Manage empoyee nie zapisuje zmian.

## Do odtworzenia
Kroki do odtworzenia zachowania:
1. Zaloguj się jako JD
2. Przejdź do zakładki Management
3. Wejdź w restaurację
4. Przesuń do dołu
5. Wybierz "Employees"
6. Kliknij ikonę długopisu do edycji
7. Wprowadź zmiany i spróbuj je zapisać

## Oczekiwane zachowanie
Zmiany zapisują się i są widoczne

https://github.com/user-attachments/assets/7ab1f500-e5f3-4411-a9ac-b8f3ab42a046

**Comment by Bambi54** [comment]
@s24937 prośba o sprawdzenie rozwiązania w dołączonym pr
