### ISSUE TITLE
[BUG]: Add new employee nie dodaje nowego pracownika

### ISSUE THREAD

**Issue by s24937** [Reservant-inc/reservant-mobile#198]
## Opisz błąd
Dla właściciela restauracji JD, dla wybranej restauracji, Add employee w Manage empoyee nie dodaje nowego pracownika.

## Do odtworzenia
Kroki do odtworzenia zachowania:
1. Zaloguj się jako JD
2. Przejdź do zakładki Management
3. Wejdź w restaurację
4. Przesuń do dołu
5. Wybierz "Employees"
6. Kliknij ikonę plusa, w celu dodania nowego pracownika
7. Wprowadź dane pracownika i spróbuj dodać pracownika

## Oczekiwane zachowanie
Pracownik dodaje się i jest widoczny na liście pracowników

https://github.com/user-attachments/assets/2e6e48f7-7d81-448d-809a-862d9d7039db

**Comment by Bambi54** [comment]
@s24937 prośba o sprawdzenie rozwiązania w dołączonym pr
