### ISSUE TITLE
[BUG]: nowa linijka zamiast nowego pola po wciśnięciu enter

### ISSUE THREAD

**Issue by Michal-Gi** [Reservant-inc/reservant-mobile#235]
- [ ] **__Sprawdziłem i nikt nie zgłosił jeszcze takiego błędu na issues__**

## Opisz błąd
pola tekstowe traktują enter na klawiaturze telefonu jako przejście do nowej linijki, a nie do następnego pola inputu

## Do odtworzenia
Kroki do odtworzenia zachowania:
1. Przejdź do Edit restaurant
2. Na klawiaturze emulatora aplikacji mobilnej naciśnij 
![image](https://github.com/user-attachments/assets/82de04e4-af94-4c7f-81a3-eea514326066)

## Oczekiwane zachowanie
przejście do następnego pola do wypełnienia

## Zrzuty ekranu (opcjonalnie)
ekrany w których ten błąd występuje
![image](https://github.com/user-attachments/assets/8b2cbba3-d19e-4124-9dfb-0e26bdaaa7a5)
![image](https://github.com/user-attachments/assets/9f034bad-5743-4f08-9ed5-8b32db4920b8)

## Dodatkowy kontekst (opcjonalnie)
Dodaj tutaj wszelkie inne informacje dotyczące problemu.

**Comment by Bambi54** [comment]
naprawione, nie podlinkuję commita bo gdzieś się zapodział, jedna linijka do zmiany w komponencie
