### ISSUE TITLE
[BUG]: Biały ekran przy wycofaniu się z edycji restauracji strzałkami wstecz

### ISSUE THREAD

**Issue by Michal-Gi** [Reservant-inc/reservant-mobile#236]
- [ ] **__Sprawdziłem i nikt nie zgłosił jeszcze takiego błędu na issues__**

## Opisz błąd
Jeżeli przejdzie się do drugiej strony edycji restauracji, a następnie wycofa się strzałkami na ekranie, to pojawi się biały ekran zamiast listy restauracji

## Do odtworzenia
Kroki do odtworzenia zachowania:
1. Przejdź do 2 panelu edycji restauracji
2. Cofnij strzałkami w lewym górnym rogu do listy restauracji

## Oczekiwane zachowanie
wyświetlenie listy restauracji

## Zrzuty ekranu (opcjonalnie)
![image](https://github.com/user-attachments/assets/dde97309-8dea-46c1-9ccd-98c2e61885b2)
![image](https://github.com/user-attachments/assets/a9d4ab88-a90d-4aa8-956e-2f08024f874b)

## Dodatkowy kontekst (opcjonalnie)
Dodaj tutaj wszelkie inne informacje dotyczące problemu.

**Comment by Bambi54** [comment]
problem polega na zbyt szybkim klikaniu przycisku przed jego zmianą

przycisk się nie zdąża zmienić ze względu na emulator oraz animację zmiany ekranu
