### ISSUE TITLE
[BUG]: Dodanie pracownika nie działa

### ISSUE THREAD

**Issue by Michal-Gi** [Reservant-inc/reservant-mobile#237]
- [ ] **__Sprawdziłem i nikt nie zgłosił jeszcze takiego błędu na issues__**

## Opisz błąd
kliknięcie sign up nic nie robi lub nie wyświetla informacji o błędzie we wprowadzonych danych

## Do odtworzenia
Kroki do odtworzenia zachowania:
1. Przejdź do Add new employee
2. Wypełnij pola formularza
3. Wciśnij Sign up

## Oczekiwane zachowanie
Dodanie pracownika i zamknięcie popupu lub wyświetlenie komunikatu o błędzie

## Zrzuty ekranu (opcjonalnie)
![image](https://github.com/user-attachments/assets/37b11cfa-f275-4daf-a477-6b2ef7ead366)

## Dodatkowy kontekst (opcjonalnie)
Dodaj tutaj wszelkie inne informacje dotyczące problemu.

**Comment by Mroxny** [comment]
Duplicate of #198
