### ISSUE TITLE
[BUG]: Nie działa logowanie jako pracownik restauracji 

### ISSUE THREAD

**Issue by s24937** [Reservant-inc/reservant-mobile#262]
## Opisz błąd
Dla restauracji John Doe's 2 zosali utworzeni pracownicy. Nie można zalogować się do aplikacji jako pracownik 

## Do odtworzenia
1. Przejdź do zaklądki logowania
2. Wpisz dane do logowania pracownika restauracji (własnego lub ze screena)
4. Zobacz błąd

## Oczekiwane zachowanie
Można zalogować się do systemu jako pracownik restauracji. 

## Zrzuty ekranu (opcjonalnie)
<img width="293" alt="image" src="https://github.com/user-attachments/assets/42bba0e2-38c1-432d-ab08-bab6c4021f77">
<img width="293" alt="image" src="https://github.com/user-attachments/assets/e6dba0a6-cf7a-45e9-aab7-28b8af55eb8d">
<img width="294" alt="image" src="https://github.com/user-attachments/assets/f779f752-949f-4f74-86a0-1010d4d06abb">

**Comment by Bambi54** [comment]
duplicate of #254
