### ISSUE TITLE
Zbyt mało issues

### ISSUE THREAD

**Issue by linewelder** [Reservant-inc/reservant-mobile#56]
Podejrzane :raised_eyebrow:

**Comment by Bambi54** [comment]
żadnych problemów nie ma, dlatego nie ma issues XD

**Comment by Mroxny** [comment]
## Czy skoro jest issues, że nie ma issues, to czy faktycznie ich nie ma?!?!

![image](https://github.com/Reservant-inc/reservant-mobile/assets/50219282/742d0159-d2cb-43e3-a648-d10e214fe229)
