### ISSUE TITLE
Kliknięcie w ikonę na navbarze ładuje activity nawet jeśli się na niej znajduemy

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-mobile#70]
![image](https://github.com/Reservant-inc/reservant-mobile/assets/50219282/a9a38ebd-0566-46cd-a8ac-d991586a8023)

**Comment by Bambi54** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bottom bar component](https://trello.com/c/IJz7WKws/97-bottom-bar-component)
