### ISSUE TITLE
Nowa grupa restauracji

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-mobile#71]
Przy tworzeniu nowej restauracji zamiast dodać się do wybranej grupy, restauracja dodaje się do nowej grupy

**Comment by Bambi54** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [dodawania do grupy - register restaurant](https://trello.com/c/HdDCWx8c/95-dodawania-do-grupy-register-restaurant)

**Comment by skrapi2011** [comment]
#73
