### ISSUE TITLE
Second step validation in RegisterRestaurantActivity

### ISSUE THREAD

**Issue by skrapi2011** [Reservant-inc/reservant-mobile#72]
Brakuje sprawdzenia, czy grupa została wybrana w drugim etapie walidacji rejestracji restauracji

**Comment by Bambi54** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [second step validation](https://trello.com/c/b5Hf0zTI/98-second-step-validation)

**Comment by skrapi2011** [comment]
#73
