### ISSUE TITLE
Poprawić niektóre resource (PL)

### ISSUE THREAD

**Issue by skrapi2011** [Reservant-inc/reservant-mobile#76]
Niektóre resource po Polsku wymagają poprawy (tak jak np. Edytuj dane lokali, podczas klikniecia w opcje pojedynczej restauracji) w Restaurant Management

Najlepiej przelecieć po różnych activity i zweryfikować różne resource'y

**Comment by Bambi54** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [poprawienie resource](https://trello.com/c/tKPTvVuj/111-poprawienie-resource)
